// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ECommerceML.Model
{
    public class ModelInput
    {
        [ColumnName("Date"), LoadColumn(0)]
        public string Date { get; set; }


        [ColumnName("Open Price"), LoadColumn(1)]
        public float Open_Price { get; set; }


        [ColumnName("High Price"), LoadColumn(2)]
        public float High_Price { get; set; }


        [ColumnName("Low Price"), LoadColumn(3)]
        public float Low_Price { get; set; }


        [ColumnName("Close Price"), LoadColumn(4)]
        public float Close_Price { get; set; }


        [ColumnName("WAP"), LoadColumn(5)]
        public float WAP { get; set; }


        [ColumnName("No.of Shares"), LoadColumn(6)]
        public float No_of_Shares { get; set; }


        [ColumnName("No. of Trades"), LoadColumn(7)]
        public float No__of_Trades { get; set; }


        [ColumnName("Total Turnover (Rs.)"), LoadColumn(8)]
        public float Total_Turnover__Rs__ { get; set; }


        [ColumnName("Deliverable Quantity"), LoadColumn(9)]
        public float Deliverable_Quantity { get; set; }


        [ColumnName("% Deli. Qty to Traded Qty"), LoadColumn(10)]
        public float __Deli__Qty_to_Traded_Qty { get; set; }


        [ColumnName("Spread High-Low"), LoadColumn(11)]
        public float Spread_High_Low { get; set; }


        [ColumnName("Spread Close-Open"), LoadColumn(12)]
        public float Spread_Close_Open { get; set; }


    }
}
